#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          df -h
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # ========================固件定制部分========================
          # 
          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 
          # 以下为定制化固件选项和说明:
          #
          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #
          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 
          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_armvirt=y
          CONFIG_TARGET_armvirt_64=y
          CONFIG_TARGET_armvirt_64_Default=y
          CONFIG_LIBCURL_COOKIES=y
          CONFIG_LIBCURL_FILE=y
          CONFIG_LIBCURL_FTP=y
          CONFIG_LIBCURL_HTTP=y
          CONFIG_LIBCURL_NO_SMB="!"
          CONFIG_LIBCURL_OPENSSL=y
          CONFIG_LIBCURL_PROXY=y
          CONFIG_OPENSSL_WITH_COMPRESSION=y
          CONFIG_OPENSSL_WITH_DTLS=y
          CONFIG_OPENSSL_WITH_EC2M=y
          CONFIG_OPENSSL_WITH_NPN=y
          CONFIG_PACKAGE_NTFS-3G_USE_LIBFUSE=y
          CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
          CONFIG_PACKAGE_TAR_BZIP2=y
          CONFIG_PACKAGE_TAR_GZIP=y
          CONFIG_PACKAGE_TAR_POSIX_ACL=y
          CONFIG_PACKAGE_TAR_XATTR=y
          CONFIG_PACKAGE_TAR_XZ=y
          CONFIG_PACKAGE_acl=y
          CONFIG_PACKAGE_attr=y
          CONFIG_PACKAGE_badblocks=y
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_blkid=y
          CONFIG_PACKAGE_btrfs-progs=y
          CONFIG_PACKAGE_bzip2=y
          CONFIG_PACKAGE_ca-bundle=y
          CONFIG_PACKAGE_chattr=y
          CONFIG_PACKAGE_chinadns-ng=y
          CONFIG_PACKAGE_coreutils-nohup=y
          CONFIG_PACKAGE_dosfstools=y
          CONFIG_PACKAGE_dumpe2fs=y
          CONFIG_PACKAGE_e2freefrag=y
          CONFIG_PACKAGE_e2fsprogs=y
          # CONFIG_PACKAGE_etherwake is not set
          CONFIG_PACKAGE_f2fs-tools=y
          CONFIG_PACKAGE_f2fsck=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_fuse-utils=y
          CONFIG_PACKAGE_gawk=y
          CONFIG_PACKAGE_getopt=y
          CONFIG_PACKAGE_haproxy=y
          # CONFIG_PACKAGE_iptables-mod-conntrack-extra is not set
          # CONFIG_PACKAGE_iptables-mod-ipopt is not set
          CONFIG_PACKAGE_kmod-fuse=y
          # CONFIG_PACKAGE_kmod-ifb is not set
          # CONFIG_PACKAGE_kmod-ipt-conntrack-extra is not set
          # CONFIG_PACKAGE_kmod-ipt-ipopt is not set
          # CONFIG_PACKAGE_kmod-sched-cake is not set
          # CONFIG_PACKAGE_kmod-sched-core is not set
          CONFIG_PACKAGE_libacl=y
          CONFIG_PACKAGE_libattr=y
          CONFIG_PACKAGE_libblkid=y
          CONFIG_PACKAGE_libbz2=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcomerr=y
          CONFIG_PACKAGE_libcurl=y
          CONFIG_PACKAGE_libext2fs=y
          CONFIG_PACKAGE_libf2fs=y
          CONFIG_PACKAGE_libfdisk=y
          CONFIG_PACKAGE_libfuse=y
          CONFIG_PACKAGE_libltdl=y
          CONFIG_PACKAGE_liblz4=y
          CONFIG_PACKAGE_liblzma=y
          CONFIG_PACKAGE_liblzo=y
          CONFIG_PACKAGE_libminiupnpc=y
          CONFIG_PACKAGE_libmount=y
          CONFIG_PACKAGE_libnatpmp=y
          CONFIG_PACKAGE_libncurses=y
          CONFIG_PACKAGE_libreadline=y
          CONFIG_PACKAGE_libsmartcols=y
          CONFIG_PACKAGE_libss=y
          CONFIG_PACKAGE_libsysfs=y
          CONFIG_PACKAGE_libtirpc=y
          CONFIG_PACKAGE_libwebsockets-full=y
          CONFIG_PACKAGE_libwrap=y
          CONFIG_PACKAGE_losetup=y
          CONFIG_PACKAGE_lsattr=y
          CONFIG_PACKAGE_lsblk=y
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          # CONFIG_PACKAGE_luci-app-autoreboot is not set
          # CONFIG_PACKAGE_luci-app-ddns is not set
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_socks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_socks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_simple-obfs=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_v2ray-plugin=y
          CONFIG_PACKAGE_luci-app-samba=y
          # CONFIG_PACKAGE_luci-app-sqm is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2 is not set
          CONFIG_PACKAGE_luci-app-transmission=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_luci-app-wol is not set
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          CONFIG_PACKAGE_luci-i18n-samba-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-transmission-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_mkf2fs=y
          CONFIG_PACKAGE_mkhfs=y
          CONFIG_PACKAGE_nfs-utils-libs=y
          CONFIG_PACKAGE_ntfs-3g=y
          CONFIG_PACKAGE_perl=y
          CONFIG_PACKAGE_perlbase-config=y
          CONFIG_PACKAGE_perlbase-essential=y
          CONFIG_PACKAGE_perlbase-re=y
          CONFIG_PACKAGE_perlbase-unicore=y
          CONFIG_PACKAGE_perlbase-utf8=y
          # CONFIG_PACKAGE_redsocks2 is not set
          CONFIG_PACKAGE_resize2fs=y
          CONFIG_PACKAGE_resolveip=y
          CONFIG_PACKAGE_samba36-server=y
          # CONFIG_PACKAGE_sqm-scripts is not set
          CONFIG_PACKAGE_squashfs-tools-mksquashfs=y
          CONFIG_PACKAGE_squashfs-tools-unsquashfs=y
          CONFIG_PACKAGE_swap-utils=y
          CONFIG_PACKAGE_sysfsutils=y
          CONFIG_PACKAGE_tar=y
          # CONFIG_PACKAGE_tc is not set
          CONFIG_PACKAGE_tcping=y
          CONFIG_PACKAGE_terminfo=y
          CONFIG_PACKAGE_transmission-daemon-openssl=y
          CONFIG_PACKAGE_transmission-web-control=y
          CONFIG_PACKAGE_ttyd=y
          CONFIG_PACKAGE_tune2fs=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_uuidgen=y
          # CONFIG_PACKAGE_vsftpd-alt is not set
          CONFIG_PACKAGE_xfs-admin=y
          CONFIG_PACKAGE_xfs-fsck=y
          CONFIG_PACKAGE_xfs-growfs=y
          CONFIG_PACKAGE_xfs-mkfs=y
          CONFIG_PACKAGE_xz=y
          CONFIG_PACKAGE_xz-utils=y
          # CONFIG_PACKAGE_zerotier is not set
          CONFIG_PERL_NOCOMMENT=y
          CONFIG_SQUASHFS_TOOLS_LZ4_SUPPORT=y
          CONFIG_SQUASHFS_TOOLS_LZO_SUPPORT=y
          CONFIG_SQUASHFS_TOOLS_XZ_SUPPORT=y
          # CONFIG_TARGET_ROOTFS_CPIOGZ is not set
          # CONFIG_TARGET_ROOTFS_INITRAMFS is not set
          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set
          EOF
          # 
          # ========================固件定制部分结束========================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
